import type { Trip } from '../types/trip'

export const placeholderTrip: Trip = {
  id: 'trip-aurora-coast',
  title: 'Aurora Coast Escape',
  slug: 'aurora-coast-escape',
  travelerId: 'traveler-oliver',
  createdAt: '2026-07-01',
  updatedAt: '2026-07-10',
  status: 'generated',
  destination: {
    id: 'dest-iceland',
    name: 'Reykjavík',
    country: 'Iceland',
    region: 'Nordic',
    latitude: 64.1466,
    longitude: -21.9426,
    timezone: 'GMT',
    climateSummary: 'Cool and bright with long evening light.',
    bestSeason: ['June', 'July', 'August'],
    description: 'A cinematic coastal retreat shaped around geothermal baths, sea views, and quiet luxury.',
  },
  traveler: {
    id: 'traveler-oliver',
    name: 'Oliver',
    email: 'oliver@example.com',
    preferences: {
      travelStyle: ['slow luxury', 'nature', 'food'],
      pace: 'balanced',
      budgetRange: 'luxury',
      interests: ['photography', 'wellness', 'architecture'],
    },
  },
  overview: {
    summary: 'A refined five-day journey built around warm pools, dramatic coastlines, and slow evenings with excellent food.',
    vibe: 'Slow luxury with cinematic landscapes',
    durationDays: 5,
    startDate: '2026-08-12',
    endDate: '2026-08-16',
  },
  itinerary: [
    {
      id: 'day-1',
      dayNumber: 1,
      date: '2026-08-12',
      title: 'Arrival in Reykjavík',
      summary: 'Ease into the trip with a private transfer, a quiet hotel check-in, and a sunset walk by the harbor.',
      activities: [
        {
          id: 'a-1',
          title: 'Private transfer to the hotel',
          description: 'A seamless arrival with time to reset after the flight.',
          category: 'adventure',
          location: 'Keflavík Airport',
          priority: 'must',
        },
        {
          id: 'a-2',
          title: 'Harbor dinner',
          description: 'Seasonal seafood with views over the water.',
          category: 'food',
          location: 'Old Harbour',
          priority: 'must',
        },
      ],
    },
    {
      id: 'day-2',
      dayNumber: 2,
      date: '2026-08-13',
      title: 'Blue Lagoon and volcanic landscapes',
      summary: 'A day shaped around geothermal relaxation and striking natural scenery.',
      activities: [
        {
          id: 'a-3',
          title: 'Blue Lagoon visit',
          description: 'A calm morning in mineral waters surrounded by lava fields.',
          category: 'wellness',
          location: 'Blue Lagoon',
          priority: 'must',
        },
        {
          id: 'a-4',
          title: 'Reykjadalur hot spring walk',
          description: 'A scenic valley walk ending with a river bath.',
          category: 'nature',
          location: 'Hengill',
          priority: 'nice-to-have',
        },
      ],
    },
    {
      id: 'day-3',
      dayNumber: 3,
      date: '2026-08-14',
      title: 'South coast photography day',
      summary: 'A cinematic route through waterfalls, black sand beaches, and cliffside viewpoints.',
      activities: [
        {
          id: 'a-5',
          title: 'Seljalandsfoss and Skógafoss',
          description: 'Two iconic waterfalls with dramatic light at the edge of the day.',
          category: 'nature',
          location: 'South Coast',
          priority: 'must',
        },
        {
          id: 'a-6',
          title: 'Dinner at a farm-to-table restaurant',
          description: 'Warm, intimate dining with local ingredients and sea views.',
          category: 'food',
          location: 'Vík',
          priority: 'must',
        },
      ],
    },
  ],
  hotel: {
    id: 'hotel-1',
    name: 'The Glass House Retreat',
    propertyType: 'boutique',
    neighborhood: 'Laugardalur',
    checkIn: '2026-08-12',
    checkOut: '2026-08-16',
    rating: 4.9,
    pricePerNight: 650,
    amenities: ['Breakfast', 'Spa', 'Airport Transfer', 'Rooftop Lounge'],
    bookingUrl: 'https://example.com/hotel',
  },
  restaurants: [
    {
      id: 'rest-1',
      name: 'ÓX',
      cuisine: 'Modern Nordic',
      neighborhood: 'Old Town',
      rating: 4.8,
      priceLevel: 'luxury',
      reservationRequired: true,
      notes: 'Book ahead for the tasting menu.',
      websiteUrl: 'https://example.com/ox',
    },
    {
      id: 'rest-2',
      name: 'Matur og Drykkur',
      cuisine: 'Seasonal Icelandic',
      neighborhood: 'Laugavegur',
      rating: 4.7,
      priceLevel: 'high',
      reservationRequired: false,
      notes: 'Excellent for a relaxed dinner.',
      websiteUrl: 'https://example.com/matur',
    },
  ],
  budget: {
    id: 'budget-1',
    currency: 'EUR',
    totalBudget: 7800,
    estimatedSpend: 7420,
    categories: {
      lodging: 2600,
      food: 1500,
      activities: 1200,
      transportation: 900,
      misc: 220,
    },
  },
  weather: [
    {
      id: 'weather-1',
      destinationId: 'dest-iceland',
      date: '2026-08-12',
      summary: 'Bright and breezy',
      temperatureHigh: 16,
      temperatureLow: 10,
      precipitationChance: 10,
      condition: 'mild',
    },
    {
      id: 'weather-2',
      destinationId: 'dest-iceland',
      date: '2026-08-14',
      summary: 'Cool with passing clouds',
      temperatureHigh: 14,
      temperatureLow: 8,
      precipitationChance: 25,
      condition: 'cloudy',
    },
  ],
  packingList: [
    { id: 'pack-1', name: 'Waterproof shell', category: 'clothing', packed: true, required: true },
    { id: 'pack-2', name: 'Passport', category: 'documents', packed: true, required: true },
    { id: 'pack-3', name: 'Power bank', category: 'tech', packed: false, required: true },
  ],
  emergencyInfo: {
    id: 'emergency-1',
    contactName: 'Lina Halldórsdóttir',
    contactPhone: '+354 555 0123',
    embassyContact: 'Embassy of Iceland',
    medicalNote: 'A local pharmacy is available in Reykjavik city center.',
    localEmergencyNumber: '112',
  },
  transportation: [
    {
      id: 'transport-1',
      mode: 'flight',
      from: 'London',
      to: 'Reykjavík',
      departureTime: '08:30',
      arrivalTime: '12:15',
      bookingReference: 'ICE-2048',
      notes: 'Direct flight in premium cabin.',
    },
    {
      id: 'transport-2',
      mode: 'transfer',
      from: 'Airport',
      to: 'Hotel',
      departureTime: '13:00',
      bookingReference: 'TRANS-77',
    },
  ],
  localTips: [
    {
      id: 'tip-1',
      title: 'Reserve thermal pools early',
      summary: 'Preferred entries tend to fill quickly during the summer.',
      category: 'practical',
      priority: 'high',
    },
    {
      id: 'tip-2',
      title: 'Carry layers',
      summary: 'Evenings are cool despite bright daylight.',
      category: 'weather',
      priority: 'medium',
    },
  ],
  metadata: {
    generatedFromPrompt: 'Five days in Iceland focused on slow luxury and coastal landscapes.',
    source: 'ai',
    tags: ['iceland', 'luxury', 'coast'],
  },
}
